name: vccinputtablet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3+1
  dropdown_button2: ^2.3.9
  flutter_switch: ^0.3.2
  dio: ^5.6.0
  intl: ^0.19.0
  slideable: ^0.0.2
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_native_spash:
  android: true
  image: "images/launch_image.png"
  android_12: 
    image: "images/launch_image.png"
  color: "#9f9f9f"
  fill: true

flutter_icons:
  android: true
  image_path: "images/logo.jpg"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
  - images/
